### ISSUE TITLE
Looks like this project is still active, any idea what lies ahead?

### ISSUE THREAD

**Issue by luzpaz** [bandang0/theia#2]
Just wondering...?

**Comment by bandang0** [comment]
Hello @luzpaz thank you for your question. This project is simulation software for gravitational interferometers, but hasn't seen new ideas in a while... Are you interested in Gaussian optics?

**Comment by luzpaz** [comment]
Not personally but there are folks in the [FreeCAD](https://forum.freecadweb.org/viewtopic.php?f=8&t=59860) community that would be.

**Comment by bandang0** [comment]
Duly noted, thanks for your contribution!
